// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BetRequest.proto

package ru.splat.messages;

public final class BetRequest {
  private BetRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Bet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 punterId = 1;</code>
     */
    int getPunterId();

    /**
     * <code>optional int32 sum = 2;</code>
     */
    int getSum();

    /**
     * <code>optional int32 localTask = 3;</code>
     */
    int getLocalTask();

    /**
     * <code>repeated int32 services = 4;</code>
     */
    java.util.List<java.lang.Integer> getServicesList();
    /**
     * <code>repeated int32 services = 4;</code>
     */
    int getServicesCount();
    /**
     * <code>repeated int32 services = 4;</code>
     */
    int getServices(int index);

    /**
     * <code>optional int64 id = 5;</code>
     */
    long getId();

    /**
     * <code>optional int64 time = 6;</code>
     */
    long getTime();

    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    java.util.List<ru.splat.messages.BetRequest.Bet.BetOutcome> 
        getBetOutcomeList();
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    ru.splat.messages.BetRequest.Bet.BetOutcome getBetOutcome(int index);
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    int getBetOutcomeCount();
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    java.util.List<? extends ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder> 
        getBetOutcomeOrBuilderList();
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder getBetOutcomeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Bet}
   */
  public  static final class Bet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Bet)
      BetOrBuilder {
    // Use Bet.newBuilder() to construct.
    private Bet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bet() {
      punterId_ = 0;
      sum_ = 0;
      localTask_ = 0;
      services_ = java.util.Collections.emptyList();
      id_ = 0L;
      time_ = 0L;
      betOutcome_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Bet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              punterId_ = input.readInt32();
              break;
            }
            case 16: {

              sum_ = input.readInt32();
              break;
            }
            case 24: {

              localTask_ = input.readInt32();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                services_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              services_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                services_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                services_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {

              id_ = input.readInt64();
              break;
            }
            case 48: {

              time_ = input.readInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                betOutcome_ = new java.util.ArrayList<ru.splat.messages.BetRequest.Bet.BetOutcome>();
                mutable_bitField0_ |= 0x00000040;
              }
              betOutcome_.add(
                  input.readMessage(ru.splat.messages.BetRequest.Bet.BetOutcome.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          services_ = java.util.Collections.unmodifiableList(services_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          betOutcome_ = java.util.Collections.unmodifiableList(betOutcome_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.splat.messages.BetRequest.internal_static_Bet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.splat.messages.BetRequest.internal_static_Bet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.splat.messages.BetRequest.Bet.class, ru.splat.messages.BetRequest.Bet.Builder.class);
    }

    public interface BetOutcomeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Bet.BetOutcome)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 eventId = 1;</code>
       */
      int getEventId();

      /**
       * <code>optional int32 id = 2;</code>
       */
      int getId();

      /**
       * <code>optional double coefficient = 3;</code>
       */
      double getCoefficient();
    }
    /**
     * Protobuf type {@code Bet.BetOutcome}
     */
    public  static final class BetOutcome extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Bet.BetOutcome)
        BetOutcomeOrBuilder {
      // Use BetOutcome.newBuilder() to construct.
      private BetOutcome(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private BetOutcome() {
        eventId_ = 0;
        id_ = 0;
        coefficient_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private BetOutcome(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                eventId_ = input.readInt32();
                break;
              }
              case 16: {

                id_ = input.readInt32();
                break;
              }
              case 25: {

                coefficient_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.splat.messages.BetRequest.internal_static_Bet_BetOutcome_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.splat.messages.BetRequest.internal_static_Bet_BetOutcome_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.splat.messages.BetRequest.Bet.BetOutcome.class, ru.splat.messages.BetRequest.Bet.BetOutcome.Builder.class);
      }

      public static final int EVENTID_FIELD_NUMBER = 1;
      private int eventId_;
      /**
       * <code>optional int32 eventId = 1;</code>
       */
      public int getEventId() {
        return eventId_;
      }

      public static final int ID_FIELD_NUMBER = 2;
      private int id_;
      /**
       * <code>optional int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int COEFFICIENT_FIELD_NUMBER = 3;
      private double coefficient_;
      /**
       * <code>optional double coefficient = 3;</code>
       */
      public double getCoefficient() {
        return coefficient_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (eventId_ != 0) {
          output.writeInt32(1, eventId_);
        }
        if (id_ != 0) {
          output.writeInt32(2, id_);
        }
        if (coefficient_ != 0D) {
          output.writeDouble(3, coefficient_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (eventId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, eventId_);
        }
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, id_);
        }
        if (coefficient_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, coefficient_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ru.splat.messages.BetRequest.Bet.BetOutcome)) {
          return super.equals(obj);
        }
        ru.splat.messages.BetRequest.Bet.BetOutcome other = (ru.splat.messages.BetRequest.Bet.BetOutcome) obj;

        boolean result = true;
        result = result && (getEventId()
            == other.getEventId());
        result = result && (getId()
            == other.getId());
        result = result && (
            java.lang.Double.doubleToLongBits(getCoefficient())
            == java.lang.Double.doubleToLongBits(
                other.getCoefficient()));
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + EVENTID_FIELD_NUMBER;
        hash = (53 * hash) + getEventId();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + COEFFICIENT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getCoefficient()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ru.splat.messages.BetRequest.Bet.BetOutcome parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ru.splat.messages.BetRequest.Bet.BetOutcome prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Bet.BetOutcome}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Bet.BetOutcome)
          ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ru.splat.messages.BetRequest.internal_static_Bet_BetOutcome_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ru.splat.messages.BetRequest.internal_static_Bet_BetOutcome_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ru.splat.messages.BetRequest.Bet.BetOutcome.class, ru.splat.messages.BetRequest.Bet.BetOutcome.Builder.class);
        }

        // Construct using ru.splat.messages.BetRequest.Bet.BetOutcome.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          eventId_ = 0;

          id_ = 0;

          coefficient_ = 0D;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ru.splat.messages.BetRequest.internal_static_Bet_BetOutcome_descriptor;
        }

        public ru.splat.messages.BetRequest.Bet.BetOutcome getDefaultInstanceForType() {
          return ru.splat.messages.BetRequest.Bet.BetOutcome.getDefaultInstance();
        }

        public ru.splat.messages.BetRequest.Bet.BetOutcome build() {
          ru.splat.messages.BetRequest.Bet.BetOutcome result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ru.splat.messages.BetRequest.Bet.BetOutcome buildPartial() {
          ru.splat.messages.BetRequest.Bet.BetOutcome result = new ru.splat.messages.BetRequest.Bet.BetOutcome(this);
          result.eventId_ = eventId_;
          result.id_ = id_;
          result.coefficient_ = coefficient_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ru.splat.messages.BetRequest.Bet.BetOutcome) {
            return mergeFrom((ru.splat.messages.BetRequest.Bet.BetOutcome)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ru.splat.messages.BetRequest.Bet.BetOutcome other) {
          if (other == ru.splat.messages.BetRequest.Bet.BetOutcome.getDefaultInstance()) return this;
          if (other.getEventId() != 0) {
            setEventId(other.getEventId());
          }
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (other.getCoefficient() != 0D) {
            setCoefficient(other.getCoefficient());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ru.splat.messages.BetRequest.Bet.BetOutcome parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ru.splat.messages.BetRequest.Bet.BetOutcome) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int eventId_ ;
        /**
         * <code>optional int32 eventId = 1;</code>
         */
        public int getEventId() {
          return eventId_;
        }
        /**
         * <code>optional int32 eventId = 1;</code>
         */
        public Builder setEventId(int value) {
          
          eventId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 eventId = 1;</code>
         */
        public Builder clearEventId() {
          
          eventId_ = 0;
          onChanged();
          return this;
        }

        private int id_ ;
        /**
         * <code>optional int32 id = 2;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>optional int32 id = 2;</code>
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 id = 2;</code>
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }

        private double coefficient_ ;
        /**
         * <code>optional double coefficient = 3;</code>
         */
        public double getCoefficient() {
          return coefficient_;
        }
        /**
         * <code>optional double coefficient = 3;</code>
         */
        public Builder setCoefficient(double value) {
          
          coefficient_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double coefficient = 3;</code>
         */
        public Builder clearCoefficient() {
          
          coefficient_ = 0D;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:Bet.BetOutcome)
      }

      // @@protoc_insertion_point(class_scope:Bet.BetOutcome)
      private static final ru.splat.messages.BetRequest.Bet.BetOutcome DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ru.splat.messages.BetRequest.Bet.BetOutcome();
      }

      public static ru.splat.messages.BetRequest.Bet.BetOutcome getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<BetOutcome>
          PARSER = new com.google.protobuf.AbstractParser<BetOutcome>() {
        public BetOutcome parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new BetOutcome(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<BetOutcome> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<BetOutcome> getParserForType() {
        return PARSER;
      }

      public ru.splat.messages.BetRequest.Bet.BetOutcome getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int PUNTERID_FIELD_NUMBER = 1;
    private int punterId_;
    /**
     * <code>optional int32 punterId = 1;</code>
     */
    public int getPunterId() {
      return punterId_;
    }

    public static final int SUM_FIELD_NUMBER = 2;
    private int sum_;
    /**
     * <code>optional int32 sum = 2;</code>
     */
    public int getSum() {
      return sum_;
    }

    public static final int LOCALTASK_FIELD_NUMBER = 3;
    private int localTask_;
    /**
     * <code>optional int32 localTask = 3;</code>
     */
    public int getLocalTask() {
      return localTask_;
    }

    public static final int SERVICES_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> services_;
    /**
     * <code>repeated int32 services = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getServicesList() {
      return services_;
    }
    /**
     * <code>repeated int32 services = 4;</code>
     */
    public int getServicesCount() {
      return services_.size();
    }
    /**
     * <code>repeated int32 services = 4;</code>
     */
    public int getServices(int index) {
      return services_.get(index);
    }
    private int servicesMemoizedSerializedSize = -1;

    public static final int ID_FIELD_NUMBER = 5;
    private long id_;
    /**
     * <code>optional int64 id = 5;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TIME_FIELD_NUMBER = 6;
    private long time_;
    /**
     * <code>optional int64 time = 6;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int BETOUTCOME_FIELD_NUMBER = 7;
    private java.util.List<ru.splat.messages.BetRequest.Bet.BetOutcome> betOutcome_;
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    public java.util.List<ru.splat.messages.BetRequest.Bet.BetOutcome> getBetOutcomeList() {
      return betOutcome_;
    }
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    public java.util.List<? extends ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder> 
        getBetOutcomeOrBuilderList() {
      return betOutcome_;
    }
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    public int getBetOutcomeCount() {
      return betOutcome_.size();
    }
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    public ru.splat.messages.BetRequest.Bet.BetOutcome getBetOutcome(int index) {
      return betOutcome_.get(index);
    }
    /**
     * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
     */
    public ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder getBetOutcomeOrBuilder(
        int index) {
      return betOutcome_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (punterId_ != 0) {
        output.writeInt32(1, punterId_);
      }
      if (sum_ != 0) {
        output.writeInt32(2, sum_);
      }
      if (localTask_ != 0) {
        output.writeInt32(3, localTask_);
      }
      if (getServicesList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(servicesMemoizedSerializedSize);
      }
      for (int i = 0; i < services_.size(); i++) {
        output.writeInt32NoTag(services_.get(i));
      }
      if (id_ != 0L) {
        output.writeInt64(5, id_);
      }
      if (time_ != 0L) {
        output.writeInt64(6, time_);
      }
      for (int i = 0; i < betOutcome_.size(); i++) {
        output.writeMessage(7, betOutcome_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (punterId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, punterId_);
      }
      if (sum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sum_);
      }
      if (localTask_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, localTask_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < services_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(services_.get(i));
        }
        size += dataSize;
        if (!getServicesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        servicesMemoizedSerializedSize = dataSize;
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, id_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, time_);
      }
      for (int i = 0; i < betOutcome_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, betOutcome_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.splat.messages.BetRequest.Bet)) {
        return super.equals(obj);
      }
      ru.splat.messages.BetRequest.Bet other = (ru.splat.messages.BetRequest.Bet) obj;

      boolean result = true;
      result = result && (getPunterId()
          == other.getPunterId());
      result = result && (getSum()
          == other.getSum());
      result = result && (getLocalTask()
          == other.getLocalTask());
      result = result && getServicesList()
          .equals(other.getServicesList());
      result = result && (getId()
          == other.getId());
      result = result && (getTime()
          == other.getTime());
      result = result && getBetOutcomeList()
          .equals(other.getBetOutcomeList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PUNTERID_FIELD_NUMBER;
      hash = (53 * hash) + getPunterId();
      hash = (37 * hash) + SUM_FIELD_NUMBER;
      hash = (53 * hash) + getSum();
      hash = (37 * hash) + LOCALTASK_FIELD_NUMBER;
      hash = (53 * hash) + getLocalTask();
      if (getServicesCount() > 0) {
        hash = (37 * hash) + SERVICES_FIELD_NUMBER;
        hash = (53 * hash) + getServicesList().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      if (getBetOutcomeCount() > 0) {
        hash = (37 * hash) + BETOUTCOME_FIELD_NUMBER;
        hash = (53 * hash) + getBetOutcomeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.splat.messages.BetRequest.Bet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.messages.BetRequest.Bet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.messages.BetRequest.Bet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.messages.BetRequest.Bet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.messages.BetRequest.Bet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.splat.messages.BetRequest.Bet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.splat.messages.BetRequest.Bet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.splat.messages.BetRequest.Bet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.splat.messages.BetRequest.Bet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.splat.messages.BetRequest.Bet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.splat.messages.BetRequest.Bet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Bet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Bet)
        ru.splat.messages.BetRequest.BetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.splat.messages.BetRequest.internal_static_Bet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.splat.messages.BetRequest.internal_static_Bet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.splat.messages.BetRequest.Bet.class, ru.splat.messages.BetRequest.Bet.Builder.class);
      }

      // Construct using ru.splat.messages.BetRequest.Bet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBetOutcomeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        punterId_ = 0;

        sum_ = 0;

        localTask_ = 0;

        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = 0L;

        time_ = 0L;

        if (betOutcomeBuilder_ == null) {
          betOutcome_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          betOutcomeBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.splat.messages.BetRequest.internal_static_Bet_descriptor;
      }

      public ru.splat.messages.BetRequest.Bet getDefaultInstanceForType() {
        return ru.splat.messages.BetRequest.Bet.getDefaultInstance();
      }

      public ru.splat.messages.BetRequest.Bet build() {
        ru.splat.messages.BetRequest.Bet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.splat.messages.BetRequest.Bet buildPartial() {
        ru.splat.messages.BetRequest.Bet result = new ru.splat.messages.BetRequest.Bet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.punterId_ = punterId_;
        result.sum_ = sum_;
        result.localTask_ = localTask_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          services_ = java.util.Collections.unmodifiableList(services_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.services_ = services_;
        result.id_ = id_;
        result.time_ = time_;
        if (betOutcomeBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            betOutcome_ = java.util.Collections.unmodifiableList(betOutcome_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.betOutcome_ = betOutcome_;
        } else {
          result.betOutcome_ = betOutcomeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.splat.messages.BetRequest.Bet) {
          return mergeFrom((ru.splat.messages.BetRequest.Bet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.splat.messages.BetRequest.Bet other) {
        if (other == ru.splat.messages.BetRequest.Bet.getDefaultInstance()) return this;
        if (other.getPunterId() != 0) {
          setPunterId(other.getPunterId());
        }
        if (other.getSum() != 0) {
          setSum(other.getSum());
        }
        if (other.getLocalTask() != 0) {
          setLocalTask(other.getLocalTask());
        }
        if (!other.services_.isEmpty()) {
          if (services_.isEmpty()) {
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureServicesIsMutable();
            services_.addAll(other.services_);
          }
          onChanged();
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (betOutcomeBuilder_ == null) {
          if (!other.betOutcome_.isEmpty()) {
            if (betOutcome_.isEmpty()) {
              betOutcome_ = other.betOutcome_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureBetOutcomeIsMutable();
              betOutcome_.addAll(other.betOutcome_);
            }
            onChanged();
          }
        } else {
          if (!other.betOutcome_.isEmpty()) {
            if (betOutcomeBuilder_.isEmpty()) {
              betOutcomeBuilder_.dispose();
              betOutcomeBuilder_ = null;
              betOutcome_ = other.betOutcome_;
              bitField0_ = (bitField0_ & ~0x00000040);
              betOutcomeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBetOutcomeFieldBuilder() : null;
            } else {
              betOutcomeBuilder_.addAllMessages(other.betOutcome_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.splat.messages.BetRequest.Bet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.splat.messages.BetRequest.Bet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int punterId_ ;
      /**
       * <code>optional int32 punterId = 1;</code>
       */
      public int getPunterId() {
        return punterId_;
      }
      /**
       * <code>optional int32 punterId = 1;</code>
       */
      public Builder setPunterId(int value) {
        
        punterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 punterId = 1;</code>
       */
      public Builder clearPunterId() {
        
        punterId_ = 0;
        onChanged();
        return this;
      }

      private int sum_ ;
      /**
       * <code>optional int32 sum = 2;</code>
       */
      public int getSum() {
        return sum_;
      }
      /**
       * <code>optional int32 sum = 2;</code>
       */
      public Builder setSum(int value) {
        
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sum = 2;</code>
       */
      public Builder clearSum() {
        
        sum_ = 0;
        onChanged();
        return this;
      }

      private int localTask_ ;
      /**
       * <code>optional int32 localTask = 3;</code>
       */
      public int getLocalTask() {
        return localTask_;
      }
      /**
       * <code>optional int32 localTask = 3;</code>
       */
      public Builder setLocalTask(int value) {
        
        localTask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 localTask = 3;</code>
       */
      public Builder clearLocalTask() {
        
        localTask_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> services_ = java.util.Collections.emptyList();
      private void ensureServicesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          services_ = new java.util.ArrayList<java.lang.Integer>(services_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 services = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getServicesList() {
        return java.util.Collections.unmodifiableList(services_);
      }
      /**
       * <code>repeated int32 services = 4;</code>
       */
      public int getServicesCount() {
        return services_.size();
      }
      /**
       * <code>repeated int32 services = 4;</code>
       */
      public int getServices(int index) {
        return services_.get(index);
      }
      /**
       * <code>repeated int32 services = 4;</code>
       */
      public Builder setServices(
          int index, int value) {
        ensureServicesIsMutable();
        services_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 4;</code>
       */
      public Builder addServices(int value) {
        ensureServicesIsMutable();
        services_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 4;</code>
       */
      public Builder addAllServices(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureServicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, services_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 4;</code>
       */
      public Builder clearServices() {
        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 5;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 5;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 5;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 6;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 6;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 6;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<ru.splat.messages.BetRequest.Bet.BetOutcome> betOutcome_ =
        java.util.Collections.emptyList();
      private void ensureBetOutcomeIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          betOutcome_ = new java.util.ArrayList<ru.splat.messages.BetRequest.Bet.BetOutcome>(betOutcome_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.splat.messages.BetRequest.Bet.BetOutcome, ru.splat.messages.BetRequest.Bet.BetOutcome.Builder, ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder> betOutcomeBuilder_;

      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public java.util.List<ru.splat.messages.BetRequest.Bet.BetOutcome> getBetOutcomeList() {
        if (betOutcomeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(betOutcome_);
        } else {
          return betOutcomeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public int getBetOutcomeCount() {
        if (betOutcomeBuilder_ == null) {
          return betOutcome_.size();
        } else {
          return betOutcomeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public ru.splat.messages.BetRequest.Bet.BetOutcome getBetOutcome(int index) {
        if (betOutcomeBuilder_ == null) {
          return betOutcome_.get(index);
        } else {
          return betOutcomeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder setBetOutcome(
          int index, ru.splat.messages.BetRequest.Bet.BetOutcome value) {
        if (betOutcomeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetOutcomeIsMutable();
          betOutcome_.set(index, value);
          onChanged();
        } else {
          betOutcomeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder setBetOutcome(
          int index, ru.splat.messages.BetRequest.Bet.BetOutcome.Builder builderForValue) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          betOutcome_.set(index, builderForValue.build());
          onChanged();
        } else {
          betOutcomeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder addBetOutcome(ru.splat.messages.BetRequest.Bet.BetOutcome value) {
        if (betOutcomeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetOutcomeIsMutable();
          betOutcome_.add(value);
          onChanged();
        } else {
          betOutcomeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder addBetOutcome(
          int index, ru.splat.messages.BetRequest.Bet.BetOutcome value) {
        if (betOutcomeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetOutcomeIsMutable();
          betOutcome_.add(index, value);
          onChanged();
        } else {
          betOutcomeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder addBetOutcome(
          ru.splat.messages.BetRequest.Bet.BetOutcome.Builder builderForValue) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          betOutcome_.add(builderForValue.build());
          onChanged();
        } else {
          betOutcomeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder addBetOutcome(
          int index, ru.splat.messages.BetRequest.Bet.BetOutcome.Builder builderForValue) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          betOutcome_.add(index, builderForValue.build());
          onChanged();
        } else {
          betOutcomeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder addAllBetOutcome(
          java.lang.Iterable<? extends ru.splat.messages.BetRequest.Bet.BetOutcome> values) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, betOutcome_);
          onChanged();
        } else {
          betOutcomeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder clearBetOutcome() {
        if (betOutcomeBuilder_ == null) {
          betOutcome_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          betOutcomeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public Builder removeBetOutcome(int index) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          betOutcome_.remove(index);
          onChanged();
        } else {
          betOutcomeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public ru.splat.messages.BetRequest.Bet.BetOutcome.Builder getBetOutcomeBuilder(
          int index) {
        return getBetOutcomeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder getBetOutcomeOrBuilder(
          int index) {
        if (betOutcomeBuilder_ == null) {
          return betOutcome_.get(index);  } else {
          return betOutcomeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public java.util.List<? extends ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder> 
           getBetOutcomeOrBuilderList() {
        if (betOutcomeBuilder_ != null) {
          return betOutcomeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(betOutcome_);
        }
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public ru.splat.messages.BetRequest.Bet.BetOutcome.Builder addBetOutcomeBuilder() {
        return getBetOutcomeFieldBuilder().addBuilder(
            ru.splat.messages.BetRequest.Bet.BetOutcome.getDefaultInstance());
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public ru.splat.messages.BetRequest.Bet.BetOutcome.Builder addBetOutcomeBuilder(
          int index) {
        return getBetOutcomeFieldBuilder().addBuilder(
            index, ru.splat.messages.BetRequest.Bet.BetOutcome.getDefaultInstance());
      }
      /**
       * <code>repeated .Bet.BetOutcome betOutcome = 7;</code>
       */
      public java.util.List<ru.splat.messages.BetRequest.Bet.BetOutcome.Builder> 
           getBetOutcomeBuilderList() {
        return getBetOutcomeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.splat.messages.BetRequest.Bet.BetOutcome, ru.splat.messages.BetRequest.Bet.BetOutcome.Builder, ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder> 
          getBetOutcomeFieldBuilder() {
        if (betOutcomeBuilder_ == null) {
          betOutcomeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ru.splat.messages.BetRequest.Bet.BetOutcome, ru.splat.messages.BetRequest.Bet.BetOutcome.Builder, ru.splat.messages.BetRequest.Bet.BetOutcomeOrBuilder>(
                  betOutcome_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          betOutcome_ = null;
        }
        return betOutcomeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Bet)
    }

    // @@protoc_insertion_point(class_scope:Bet)
    private static final ru.splat.messages.BetRequest.Bet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.splat.messages.BetRequest.Bet();
    }

    public static ru.splat.messages.BetRequest.Bet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bet>
        PARSER = new com.google.protobuf.AbstractParser<Bet>() {
      public Bet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Bet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bet> getParserForType() {
      return PARSER;
    }

    public ru.splat.messages.BetRequest.Bet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Bet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Bet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Bet_BetOutcome_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Bet_BetOutcome_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020BetRequest.proto\"\310\001\n\003Bet\022\020\n\010punterId\030\001" +
      " \001(\005\022\013\n\003sum\030\002 \001(\005\022\021\n\tlocalTask\030\003 \001(\005\022\020\n\010" +
      "services\030\004 \003(\005\022\n\n\002id\030\005 \001(\003\022\014\n\004time\030\006 \001(\003" +
      "\022#\n\nbetOutcome\030\007 \003(\0132\017.Bet.BetOutcome\032>\n" +
      "\nBetOutcome\022\017\n\007eventId\030\001 \001(\005\022\n\n\002id\030\002 \001(\005" +
      "\022\023\n\013coefficient\030\003 \001(\001B\037\n\021ru.splat.messag" +
      "esB\nBetRequestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Bet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Bet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Bet_descriptor,
        new java.lang.String[] { "PunterId", "Sum", "LocalTask", "Services", "Id", "Time", "BetOutcome", });
    internal_static_Bet_BetOutcome_descriptor =
      internal_static_Bet_descriptor.getNestedTypes().get(0);
    internal_static_Bet_BetOutcome_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Bet_BetOutcome_descriptor,
        new java.lang.String[] { "EventId", "Id", "Coefficient", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
