// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package ru.splat.messages;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServiceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServiceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 services = 1;</code>
     */
    java.util.List<java.lang.Integer> getServicesList();
    /**
     * <code>repeated int32 services = 1;</code>
     */
    int getServicesCount();
    /**
     * <code>repeated int32 services = 1;</code>
     */
    int getServices(int index);

    /**
     * <code>optional string stringAttachment = 2;</code>
     */
    java.lang.String getStringAttachment();
    /**
     * <code>optional string stringAttachment = 2;</code>
     */
    com.google.protobuf.ByteString
        getStringAttachmentBytes();

    /**
     * <code>optional int64 longAttachment = 3;</code>
     */
    long getLongAttachment();

    /**
     * <code>optional double doubleAttachment = 4;</code>
     */
    double getDoubleAttachment();

    /**
     * <code>optional bool booleanAttachment = 5;</code>
     */
    boolean getBooleanAttachment();

    /**
     * <code>optional int32 result = 6;</code>
     */
    int getResult();

    public ru.splat.messages.Response.ServiceResponse.AttachmentOneofCase getAttachmentOneofCase();
  }
  /**
   * Protobuf type {@code ServiceResponse}
   */
  public  static final class ServiceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServiceResponse)
      ServiceResponseOrBuilder {
    // Use ServiceResponse.newBuilder() to construct.
    private ServiceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceResponse() {
      services_ = java.util.Collections.emptyList();
      result_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServiceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                services_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              services_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                services_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                services_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              attachmentOneofCase_ = 2;
              attachmentOneof_ = s;
              break;
            }
            case 24: {
              attachmentOneofCase_ = 3;
              attachmentOneof_ = input.readInt64();
              break;
            }
            case 33: {
              attachmentOneofCase_ = 4;
              attachmentOneof_ = input.readDouble();
              break;
            }
            case 40: {
              attachmentOneofCase_ = 5;
              attachmentOneof_ = input.readBool();
              break;
            }
            case 48: {

              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          services_ = java.util.Collections.unmodifiableList(services_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.splat.messages.Response.internal_static_ServiceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.splat.messages.Response.internal_static_ServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.splat.messages.Response.ServiceResponse.class, ru.splat.messages.Response.ServiceResponse.Builder.class);
    }

    private int bitField0_;
    private int attachmentOneofCase_ = 0;
    private java.lang.Object attachmentOneof_;
    public enum AttachmentOneofCase
        implements com.google.protobuf.Internal.EnumLite {
      STRINGATTACHMENT(2),
      LONGATTACHMENT(3),
      DOUBLEATTACHMENT(4),
      BOOLEANATTACHMENT(5),
      ATTACHMENTONEOF_NOT_SET(0);
      private final int value;
      private AttachmentOneofCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static AttachmentOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static AttachmentOneofCase forNumber(int value) {
        switch (value) {
          case 2: return STRINGATTACHMENT;
          case 3: return LONGATTACHMENT;
          case 4: return DOUBLEATTACHMENT;
          case 5: return BOOLEANATTACHMENT;
          case 0: return ATTACHMENTONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public AttachmentOneofCase
    getAttachmentOneofCase() {
      return AttachmentOneofCase.forNumber(
          attachmentOneofCase_);
    }

    public static final int SERVICES_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> services_;
    /**
     * <code>repeated int32 services = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getServicesList() {
      return services_;
    }
    /**
     * <code>repeated int32 services = 1;</code>
     */
    public int getServicesCount() {
      return services_.size();
    }
    /**
     * <code>repeated int32 services = 1;</code>
     */
    public int getServices(int index) {
      return services_.get(index);
    }
    private int servicesMemoizedSerializedSize = -1;

    public static final int STRINGATTACHMENT_FIELD_NUMBER = 2;
    /**
     * <code>optional string stringAttachment = 2;</code>
     */
    public java.lang.String getStringAttachment() {
      java.lang.Object ref = "";
      if (attachmentOneofCase_ == 2) {
        ref = attachmentOneof_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (attachmentOneofCase_ == 2) {
          attachmentOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stringAttachment = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStringAttachmentBytes() {
      java.lang.Object ref = "";
      if (attachmentOneofCase_ == 2) {
        ref = attachmentOneof_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (attachmentOneofCase_ == 2) {
          attachmentOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGATTACHMENT_FIELD_NUMBER = 3;
    /**
     * <code>optional int64 longAttachment = 3;</code>
     */
    public long getLongAttachment() {
      if (attachmentOneofCase_ == 3) {
        return (java.lang.Long) attachmentOneof_;
      }
      return 0L;
    }

    public static final int DOUBLEATTACHMENT_FIELD_NUMBER = 4;
    /**
     * <code>optional double doubleAttachment = 4;</code>
     */
    public double getDoubleAttachment() {
      if (attachmentOneofCase_ == 4) {
        return (java.lang.Double) attachmentOneof_;
      }
      return 0D;
    }

    public static final int BOOLEANATTACHMENT_FIELD_NUMBER = 5;
    /**
     * <code>optional bool booleanAttachment = 5;</code>
     */
    public boolean getBooleanAttachment() {
      if (attachmentOneofCase_ == 5) {
        return (java.lang.Boolean) attachmentOneof_;
      }
      return false;
    }

    public static final int RESULT_FIELD_NUMBER = 6;
    private int result_;
    /**
     * <code>optional int32 result = 6;</code>
     */
    public int getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getServicesList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(servicesMemoizedSerializedSize);
      }
      for (int i = 0; i < services_.size(); i++) {
        output.writeInt32NoTag(services_.get(i));
      }
      if (attachmentOneofCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, attachmentOneof_);
      }
      if (attachmentOneofCase_ == 3) {
        output.writeInt64(
            3, (long)((java.lang.Long) attachmentOneof_));
      }
      if (attachmentOneofCase_ == 4) {
        output.writeDouble(
            4, (double)((java.lang.Double) attachmentOneof_));
      }
      if (attachmentOneofCase_ == 5) {
        output.writeBool(
            5, (boolean)((java.lang.Boolean) attachmentOneof_));
      }
      if (result_ != 0) {
        output.writeInt32(6, result_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < services_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(services_.get(i));
        }
        size += dataSize;
        if (!getServicesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        servicesMemoizedSerializedSize = dataSize;
      }
      if (attachmentOneofCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, attachmentOneof_);
      }
      if (attachmentOneofCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(
              3, (long)((java.lang.Long) attachmentOneof_));
      }
      if (attachmentOneofCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              4, (double)((java.lang.Double) attachmentOneof_));
      }
      if (attachmentOneofCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              5, (boolean)((java.lang.Boolean) attachmentOneof_));
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, result_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.splat.messages.Response.ServiceResponse)) {
        return super.equals(obj);
      }
      ru.splat.messages.Response.ServiceResponse other = (ru.splat.messages.Response.ServiceResponse) obj;

      boolean result = true;
      result = result && getServicesList()
          .equals(other.getServicesList());
      result = result && (getResult()
          == other.getResult());
      result = result && getAttachmentOneofCase().equals(
          other.getAttachmentOneofCase());
      if (!result) return false;
      switch (attachmentOneofCase_) {
        case 2:
          result = result && getStringAttachment()
              .equals(other.getStringAttachment());
          break;
        case 3:
          result = result && (getLongAttachment()
              == other.getLongAttachment());
          break;
        case 4:
          result = result && (
              java.lang.Double.doubleToLongBits(getDoubleAttachment())
              == java.lang.Double.doubleToLongBits(
                  other.getDoubleAttachment()));
          break;
        case 5:
          result = result && (getBooleanAttachment()
              == other.getBooleanAttachment());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getServicesCount() > 0) {
        hash = (37 * hash) + SERVICES_FIELD_NUMBER;
        hash = (53 * hash) + getServicesList().hashCode();
      }
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      switch (attachmentOneofCase_) {
        case 2:
          hash = (37 * hash) + STRINGATTACHMENT_FIELD_NUMBER;
          hash = (53 * hash) + getStringAttachment().hashCode();
          break;
        case 3:
          hash = (37 * hash) + LONGATTACHMENT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getLongAttachment());
          break;
        case 4:
          hash = (37 * hash) + DOUBLEATTACHMENT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getDoubleAttachment()));
          break;
        case 5:
          hash = (37 * hash) + BOOLEANATTACHMENT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBooleanAttachment());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.splat.messages.Response.ServiceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.messages.Response.ServiceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.messages.Response.ServiceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.splat.messages.Response.ServiceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.splat.messages.Response.ServiceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.splat.messages.Response.ServiceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.splat.messages.Response.ServiceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.splat.messages.Response.ServiceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.splat.messages.Response.ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.splat.messages.Response.ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.splat.messages.Response.ServiceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServiceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServiceResponse)
        ru.splat.messages.Response.ServiceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.splat.messages.Response.internal_static_ServiceResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.splat.messages.Response.internal_static_ServiceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.splat.messages.Response.ServiceResponse.class, ru.splat.messages.Response.ServiceResponse.Builder.class);
      }

      // Construct using ru.splat.messages.Response.ServiceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;

        attachmentOneofCase_ = 0;
        attachmentOneof_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.splat.messages.Response.internal_static_ServiceResponse_descriptor;
      }

      public ru.splat.messages.Response.ServiceResponse getDefaultInstanceForType() {
        return ru.splat.messages.Response.ServiceResponse.getDefaultInstance();
      }

      public ru.splat.messages.Response.ServiceResponse build() {
        ru.splat.messages.Response.ServiceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.splat.messages.Response.ServiceResponse buildPartial() {
        ru.splat.messages.Response.ServiceResponse result = new ru.splat.messages.Response.ServiceResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          services_ = java.util.Collections.unmodifiableList(services_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.services_ = services_;
        if (attachmentOneofCase_ == 2) {
          result.attachmentOneof_ = attachmentOneof_;
        }
        if (attachmentOneofCase_ == 3) {
          result.attachmentOneof_ = attachmentOneof_;
        }
        if (attachmentOneofCase_ == 4) {
          result.attachmentOneof_ = attachmentOneof_;
        }
        if (attachmentOneofCase_ == 5) {
          result.attachmentOneof_ = attachmentOneof_;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        result.attachmentOneofCase_ = attachmentOneofCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.splat.messages.Response.ServiceResponse) {
          return mergeFrom((ru.splat.messages.Response.ServiceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.splat.messages.Response.ServiceResponse other) {
        if (other == ru.splat.messages.Response.ServiceResponse.getDefaultInstance()) return this;
        if (!other.services_.isEmpty()) {
          if (services_.isEmpty()) {
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServicesIsMutable();
            services_.addAll(other.services_);
          }
          onChanged();
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        switch (other.getAttachmentOneofCase()) {
          case STRINGATTACHMENT: {
            attachmentOneofCase_ = 2;
            attachmentOneof_ = other.attachmentOneof_;
            onChanged();
            break;
          }
          case LONGATTACHMENT: {
            setLongAttachment(other.getLongAttachment());
            break;
          }
          case DOUBLEATTACHMENT: {
            setDoubleAttachment(other.getDoubleAttachment());
            break;
          }
          case BOOLEANATTACHMENT: {
            setBooleanAttachment(other.getBooleanAttachment());
            break;
          }
          case ATTACHMENTONEOF_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.splat.messages.Response.ServiceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.splat.messages.Response.ServiceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int attachmentOneofCase_ = 0;
      private java.lang.Object attachmentOneof_;
      public AttachmentOneofCase
          getAttachmentOneofCase() {
        return AttachmentOneofCase.forNumber(
            attachmentOneofCase_);
      }

      public Builder clearAttachmentOneof() {
        attachmentOneofCase_ = 0;
        attachmentOneof_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.util.List<java.lang.Integer> services_ = java.util.Collections.emptyList();
      private void ensureServicesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          services_ = new java.util.ArrayList<java.lang.Integer>(services_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getServicesList() {
        return java.util.Collections.unmodifiableList(services_);
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public int getServicesCount() {
        return services_.size();
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public int getServices(int index) {
        return services_.get(index);
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public Builder setServices(
          int index, int value) {
        ensureServicesIsMutable();
        services_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public Builder addServices(int value) {
        ensureServicesIsMutable();
        services_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public Builder addAllServices(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureServicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, services_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public Builder clearServices() {
        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <code>optional string stringAttachment = 2;</code>
       */
      public java.lang.String getStringAttachment() {
        java.lang.Object ref = "";
        if (attachmentOneofCase_ == 2) {
          ref = attachmentOneof_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (attachmentOneofCase_ == 2) {
            attachmentOneof_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stringAttachment = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStringAttachmentBytes() {
        java.lang.Object ref = "";
        if (attachmentOneofCase_ == 2) {
          ref = attachmentOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (attachmentOneofCase_ == 2) {
            attachmentOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stringAttachment = 2;</code>
       */
      public Builder setStringAttachment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  attachmentOneofCase_ = 2;
        attachmentOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringAttachment = 2;</code>
       */
      public Builder clearStringAttachment() {
        if (attachmentOneofCase_ == 2) {
          attachmentOneofCase_ = 0;
          attachmentOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string stringAttachment = 2;</code>
       */
      public Builder setStringAttachmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        attachmentOneofCase_ = 2;
        attachmentOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int64 longAttachment = 3;</code>
       */
      public long getLongAttachment() {
        if (attachmentOneofCase_ == 3) {
          return (java.lang.Long) attachmentOneof_;
        }
        return 0L;
      }
      /**
       * <code>optional int64 longAttachment = 3;</code>
       */
      public Builder setLongAttachment(long value) {
        attachmentOneofCase_ = 3;
        attachmentOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 longAttachment = 3;</code>
       */
      public Builder clearLongAttachment() {
        if (attachmentOneofCase_ == 3) {
          attachmentOneofCase_ = 0;
          attachmentOneof_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional double doubleAttachment = 4;</code>
       */
      public double getDoubleAttachment() {
        if (attachmentOneofCase_ == 4) {
          return (java.lang.Double) attachmentOneof_;
        }
        return 0D;
      }
      /**
       * <code>optional double doubleAttachment = 4;</code>
       */
      public Builder setDoubleAttachment(double value) {
        attachmentOneofCase_ = 4;
        attachmentOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double doubleAttachment = 4;</code>
       */
      public Builder clearDoubleAttachment() {
        if (attachmentOneofCase_ == 4) {
          attachmentOneofCase_ = 0;
          attachmentOneof_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bool booleanAttachment = 5;</code>
       */
      public boolean getBooleanAttachment() {
        if (attachmentOneofCase_ == 5) {
          return (java.lang.Boolean) attachmentOneof_;
        }
        return false;
      }
      /**
       * <code>optional bool booleanAttachment = 5;</code>
       */
      public Builder setBooleanAttachment(boolean value) {
        attachmentOneofCase_ = 5;
        attachmentOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool booleanAttachment = 5;</code>
       */
      public Builder clearBooleanAttachment() {
        if (attachmentOneofCase_ == 5) {
          attachmentOneofCase_ = 0;
          attachmentOneof_ = null;
          onChanged();
        }
        return this;
      }

      private int result_ ;
      /**
       * <code>optional int32 result = 6;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 6;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 6;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ServiceResponse)
    }

    // @@protoc_insertion_point(class_scope:ServiceResponse)
    private static final ru.splat.messages.Response.ServiceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.splat.messages.Response.ServiceResponse();
    }

    public static ru.splat.messages.Response.ServiceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServiceResponse>() {
      public ServiceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServiceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceResponse> getParserForType() {
      return PARSER;
    }

    public ru.splat.messages.Response.ServiceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Response.proto\"\266\001\n\017ServiceResponse\022\020\n\010" +
      "services\030\001 \003(\005\022\032\n\020stringAttachment\030\002 \001(\t" +
      "H\000\022\030\n\016longAttachment\030\003 \001(\003H\000\022\032\n\020doubleAt" +
      "tachment\030\004 \001(\001H\000\022\033\n\021booleanAttachment\030\005 " +
      "\001(\010H\000\022\016\n\006result\030\006 \001(\005B\022\n\020attachment_oneo" +
      "fB\035\n\021ru.splat.messagesB\010Responseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceResponse_descriptor,
        new java.lang.String[] { "Services", "StringAttachment", "LongAttachment", "DoubleAttachment", "BooleanAttachment", "Result", "AttachmentOneof", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
